ALTER TABLE balance_snapshot ADD COLUMN origin VARCHAR(20) NOT NULL DEFAULT 'OBSERVED';

CREATE TABLE fire_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL UNIQUE REFERENCES family_member(id) ON DELETE CASCADE,
    annual_expenses NUMERIC(20,2) NOT NULL,
    monthly_savings NUMERIC(20,2) NOT NULL,
    safe_withdrawal_rate NUMERIC(8,6) NOT NULL,
    current_age INTEGER,
    retirement_age INTEGER,
    return_mode VARCHAR(20) NOT NULL,
    manual_return_rate NUMERIC(8,6)
);

CREATE TABLE rebalance_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES family_member(id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    ticker VARCHAR(30) NOT NULL,
    target_percent NUMERIC(8,4) NOT NULL,
    CONSTRAINT uk_rebalance_target_member_account_ticker UNIQUE (member_id, account_id, ticker)
);
